---
title: "Complex Bootstrap Continuous"
author: "Tucker Morgan - tlm2152"
date: "2/18/2022"
output: pdf_document
---

## Generating Data
```{r data generation}
source("./shared_code/data_gen_continuous.R")
```

## Complex Bootstrap
```{r complex boot function, warning = FALSE, message = FALSE}
generate_boots <- function(df, iter = 100, seeds = seed_vec){
  pb3$tick()
  boot_samples <- list()
  matched_boot_df <- list()
  boot_ate <- tibble()
  
    for (i in 1:iter) {
      set.seed(seeds[[i]])
      
      boot_samples[[i]] <- sample_n(df, nrow(df), replace = TRUE)
      
      matched <- matchit(A ~ L2 + L3, 
                         data = boot_samples[[i]], 
                         distance = "glm", 
                         link = "logit",
                         method = "nearest", 
                         ratio = 1)
      
      matched_boot_df[[i]] <- match.data(matched, distance = "ps")
      
      bootmod <- glm(Y ~ A + ps, data = matched_boot_df[[i]], 
                     weights = weights)
      
      sum_bootmod <- summary(bootmod)
      
      estimate_val <- sum_bootmod$coef[2,1]
      to_bind_rows_estimate <- tibble(estimate = estimate_val)
      boot_ate <- bind_rows(boot_ate, to_bind_rows_estimate)
    }

       results <-
       tibble(
         avg_trt_eff = mean(boot_ate$estimate),
         sd_ate = sd(boot_ate$estimate)
       )

  return(results)
}
```

```{r running complex boots}
nb_tib <- tibble(nb = no_boot_list)

pb3 <- progress_bar$new(format = "bootstrapping... [:bar] :percent eta: :eta", total = nrow(nb_tib))

# iter = 500 later

result_list <- nb_tib %>% mutate(res_tib = map(.x = nb, ~generate_boots(.x, iter = 100)))

fin_estimate_df <- 
  result_list %>% 
  unnest(res_tib) %>% 
  select(-nb) %>% 
  mutate(seq = c(1:nrow(fin_estimate_df)))
```

## Confidence Intervals Coverage Rates

```{r coverage rate calculation}
cvg_rate <- function(df){
  res = df %>% 
    mutate(ci_low = avg_trt_eff - 1.96*sd(avg_trt_eff),
         ci_high = avg_trt_eff + 1.96*sd(avg_trt_eff),
         covered = case_when(
           ci_low <= beta1 & ci_high >= beta1 ~ 1,
                                         TRUE ~ 0
         ))
  
  return(sum(res$covered) / nrow(res))
}

cvg_plot <- function(df){
  res = df %>% 
    mutate(ci_low = avg_trt_eff - 1.96*sd(avg_trt_eff),
         ci_high = avg_trt_eff + 1.96*sd(avg_trt_eff),
         covered = case_when(
           ci_low <= beta1 & ci_high >= beta1 ~ 1,
                                         TRUE ~ 0
         ))
  
  plot = res %>% 
    ggplot(aes(x = avg_trt_eff, y = seq)) +
    geom_point() +
    geom_errorbar(aes(xmin = ci_low, xmax = ci_high)) +
    geom_vline(xintercept = beta1, linetype = "dashed")
  
  return(plot)
}

cvg_rate(fin_estimate_df)
cvg_plot(fin_estimate_df)
```

