---
title: "Binary_Simulation_v3"
author: "Waveley"
date: "2022-02-17"
output: pdf_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE, eval = FALSE, include = FALSE}
source("./shared_code/setup.R")
```

## Generating 100 No Boot Samples
```{r calling functions}
source('./shared_code/data_gen_binary.R')
```

## Checking Distribution of Treatment Rate
```{r distribution of treatment rate}
hist(map_dbl(1:length(no_boot_list), function(i) mean(no_boot_list[[i]]$A)), 
     main = "Hist of Treatment Dist",
     xlab = "Treat Rate",
     ylab = "Count")
```

## No boot bias distribution
```{r function for no boot bias}
no_boot_result <-
  function(n)  {
  b <- vector()
    for (i in 1:n) {
  a <- glm(Y ~ A + L2 + L3, data = no_boot_list[[i]], family = "binomial")
  b[i] <- summary(a)$coef[2,1]
}
return(b)    
  }

no_boot_OR <- no_boot_result(100)
```

```{r no boot bias plot}
no_boot_bias <- 
  tibble(no_boot_OR = no_boot_OR) %>%
  summarise(bias = (no_boot_OR - 0.767))

no_boot_bias %>%
  ggplot(aes(x = bias)) +
  geom_histogram(fill = "light blue", bins = 15, color = "black") +
  geom_density(aes(y = ..density..*5), colour = "red", 
               fill = "black", alpha = 0.3) + 
  geom_vline(xintercept = mean(no_boot_bias$bias), linetype = "dashed") +
  labs(title = "Distribution of no boot mean log OR bias", 
       caption = "Ideal center: 0", x = "Log OR", y = "Frequency") + 
  theme(
  plot.title = element_text(color = "blue", size = 11, face = "bold"),
  plot.caption = element_text(color = "orange", face = "italic")
  )
```

## Implementing nearest-neighbor matching (NNM)
```{r implement NNM, warning=FALSE}
df <- no_boot_list

# could possible turn this into a function later.
matched_df <- list()
# mean_treat_save <- rep(0, length(df))
# match_save <- rep(0, length(df))
for (i in 1:length(df)) {
  
  matched <- matchit(A ~ L1 + L2 + L3, 
                          data = df[[i]], 
                          distance = "glm", 
                          link = "logit",
                          method = "nearest", 
                          ratio = 1) # perform NNM
  
  matched_df[[i]] <- match.data(matched, distance = "ps") 
  # mean_treat_save[i] <- (5000*mean(df[[i]]$A)*2)
  # match_save[i] <- (match.data(matched, distance = "ps")  %>% 
  #                     select(subclass) %>% unique() %>% summarize(n=n()) %>% pull(n))*2
}

```

## simple Bootstrap
```{r simple bootstrap}
# creating the tibble to apply map function
matched_tib <-
  tibble(data = matched_df)

# ### function to iterate glm over a list, to be used in purr:map ###
# returns tibble of parameter estimates and standard errors.

outcome_model_list <- function(list) {
  tib_coef <- tibble()
  pb3$tick()
  for (i in 1:length(list)) {
    mod <- glm(Y ~ A + ps, 
               data = list[[i]], 
               weights = weights, 
               family = "binomial") %>% summary()
    coefs <- mod$coefficients[2,1:2]
    tib_coef <- bind_rows(tib_coef, tibble(estimate = coefs[1], se = coefs[2]))
  }
    return(tib_coef)
}

# ### input matched dataframe, output however many bootstrapped samples you want ###
# first, set seed vector for reproducibility


# now, define function

seed_vec_2 <- rnorm(100000, mean = 0, sd = 10000) %>% round(0) %>% unique()

simple_boot <- function(df, n, size = 500, seeds = seed_vec_2){
  boots <- list()
  pb2$tick()
  for (i in 1:n) {
  set.seed(seeds[i])
  boots[[i]] <- 
    df %>% 
    filter(subclass %in% sample(levels(subclass), 
                                size, 
                                replace =  TRUE))
  }
  return(boots)
}


# adding progress bars for sanity
pb2 <- progress_bar$new(format = "bootstrapping... [:bar]", total = nrow(matched_tib))
pb3 <- progress_bar$new(format = "performing glm... [:bar]", total = nrow(matched_tib))

# creating booted tibbles, applying functions through purr:map.
boot_tib <- 
  matched_tib %>% 
  mutate(
    boots = map(.x = data, ~simple_boot(.x, n = 100))
    ) %>%
  mutate(coef = map(.x = boots, ~outcome_model_list(.x)))

```

## Unnesting bootstrap coefficients
```{r unnesting bootstrap coefficients}
boot_estimates <- 
  boot_tib %>% 
  mutate(seq = seq(1:nrow(boot_tib))) %>% 
  select(coef, seq) %>% unnest(coef)
```

## Summary of 1000 bootstrap of 100 no boot
```{r summarizing bootstrap data}
boot_result <-
  boot_estimates %>%
  group_by(seq) %>%
  summarize(mean_log_OR = mean(estimate), sd_log_OR = sd(estimate),
            bias = (mean_log_OR - 0.767)) # should be updated
fig1 <-
  boot_result %>%
  ggplot(aes(x = sd_log_OR, color = sd_log_OR)) +
  geom_histogram(fill = "light blue",  bins = 12,  color = "black") +
  geom_density(aes(y = ..density..*0.4), colour = "red", 
               fill = "black", alpha = 0.3) + 
  geom_vline(xintercept = mean(boot_result$sd_log_OR), linetype = "dashed") + 
  labs(title = "Distribution of 100 SD of mean log OR",
       subtitle = "Distribution of bias", x = "Log OR", y = "Frequency",
       caption = "Ideal shape: right-skewed shape with mode at 0") + 
  theme(
  plot.title = element_text(color = "blue", size = 11, face = "bold"),
  plot.subtitle = element_text(color = "black"),
  plot.caption = element_text(color = "orange", face = "italic")
  )

fig2 <- 
  boot_result %>%
  ggplot(aes(x = mean_log_OR)) + 
  geom_histogram(fill = "light blue", bins = 12, color = "black") +
  geom_density(aes(y = ..density..*6), colour = "red", 
               fill = "black", alpha = 0.3) + 
  geom_vline(xintercept = mean(boot_result$mean_log_OR), linetype = "dashed") +
  labs(title = "Distribution of 100 mean log OR", 
       caption = "Ideal center: 0.767 (true log OR)", x = "Log OR", y = "Frequency") +# ideal should be updated
  theme(
  plot.title = element_text(color = "blue", size = 11, face = "bold"),
  plot.caption = element_text(color = "orange", face = "italic")
  )

plot_grid(fig1, fig2)
```


```{r}
fig3 <- 
  boot_result %>%
  ggplot(aes(x = bias)) + 
  geom_histogram(fill = "light blue", bins = 15, color = "black") +
  geom_density(aes(y = ..density..*5), colour = "red", 
               fill = "black", alpha = 0.3) + 
  geom_vline(xintercept = mean(boot_result$bias), linetype = "dashed") +
  labs(title = "Distribution of mean log OR bias", 
       caption = "Ideal center: 0", x = "Log OR", y = "Frequency") + 
  theme(
  plot.title = element_text(color = "blue", size = 11, face = "bold"),
  plot.caption = element_text(color = "orange", face = "italic")
  )

fig3
```

## 100 Confidence Intervals Coverage Rate
```{r}
CI_coverate_rate <- function(nboot){
  boot_CI_log_OR <- list()
  count_true <- list()
  
  for (i in 1:nboot) {
     boot_CI_log_OR[[i]] <- 
       c(boot_result$mean_log_OR[i] - 1.96*boot_result$sd_log_OR,
         boot_result$mean_log_OR[i] + 1.96*boot_result$sd_log_OR)
     
      count_true[i] <- 
        between(0.767, range(boot_CI_log_OR[[i]])[1], range(boot_CI_log_OR[[i]])[2]) 
  }
  
  result = 
    as.vector(unlist(count_true)) %>% 
    sum() 
  result = paste0("CI coverage rate:", result, "%")
  
  return(result)
}

CI_coverate_rate(100)
```


