---
title: "Binary_Simulation_v2"
author: "Hun"
date: "2/15/2022"
output: html_document
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(simstudy)
library(MatchIt)
library(dplyr)
library(progress) 

# set knitr defaults
knitr::opts_chunk$set(
    echo      = TRUE
  , fig.align = "center"
  , fig.width = 6
  , fig.asp   = .6
  , out.width = "90%"
)

# set theme defaults
theme_set(
  theme_bw() +
  theme(
    legend.position = "bottom"
    , plot.title    = element_text(hjust = 0.5)
    , plot.subtitle = element_text(hjust = 0.5)
    , plot.caption  = element_text(hjust = 0.0)
  )
)

# set color scale defaults
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill   = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete   = scale_fill_viridis_d
```


## Generating covariates and finding coefficits for covariates in propensity model. 

```{r}

covariate_coef <- function(desired_prop) {
  
   alpha_0 = log(desired_prop/(1 - desired_prop))
   
   coef_L1 <- sample(cov_df$L1, 10000, replace = TRUE)
   
   coef_L2 <- sample(cov_df$L2, 10000, replace = TRUE)
   
   coef_L3 <- sample(cov_df$L3, 10000, replace = TRUE)
   
   A_logit <- vector(mode = "list",length = length(coef_L2))
   p_A <-  vector(mode = "numeric",length = length(coef_L2))
   
   u <- alpha_0 + coef_L1[1]*cov_df$L1 + coef_L2[1]*cov_df$L2 - coef_L3[1]*cov_df$L3
   
   p_A[1] <-  mean(exp(u)/(1 + exp(u)))
   
   tol <- 0.001
   
   i = 1
   
   while (abs(p_A[i] - 0.14) > tol) {
     
     i = i + 1
     
     A_logit[[i]] <- 
       alpha_0 + coef_L1[i]*cov_df$L1 + coef_L2[i]*cov_df$L2 - coef_L3[i]*cov_df$L3
     
     p_A[i] <- mean(exp(A_logit[[i]])/(1 + exp(A_logit[[i]])))
     
     if (abs(p_A[i] - 0.14) < tol) {
       mean_treated_proportion <- p_A[i]
       desired_coef_L1 <- coef_L1[i]
       desired_coef_L2 <- coef_L2[i]
       desired_coef_L3 <- coef_L3[i]
     }
     
     if (i > length(coef_L2)) {
       stop("You need better coverage, mate.")
    }
     
   }
   
   return(tibble(alpha_0,  mean_treated_proportion, 
            desired_coef_L1, desired_coef_L2, desired_coef_L3))
}


```

## Creating Covariates data frame list
```{r}
seed_vec <- rnorm(100000, mean = 0, sd = 100) %>% round(0) %>% unique()

covariate_df <- function(seeds, n){
    cov_df <- list()
    
    for (i in 1:n) {
    
    set.seed(seeds[i])
    pre_data <- defData(varname = "L1", formula = "0", variance = 1,
                dist = "normal")
    
    pre_data <- defData(pre_data, varname = "L2", formula = "0", variance = 1,
                dist = "normal")
    
    pre_data <- defData(pre_data, varname = "L3", formula = "0", variance = 1,
                dist = "normal")
    
    cov_df[[i]] <- genData(5000, pre_data)
  
    }
  return(cov_df)
}


cov_df <- covariate_df(seed_vec, 2)
```


## Generating 100 no boot samples

```{r}

generate_no_boot_data <- function(n, size = 5000, seeds = seed_vec) {
  
  df <- list()
  
  pb <- progress_bar$new(format = "generating data... [:bar]", total = n)
  
    for (i in 1:n) {
    pb$tick()
    set.seed(seeds[i])
    
    cov_df <- cov_df[[i]]
    
    cov_coef_df <- covariate_coef(0.14)
    
    L1_coef <- cov_coef_df$desired_coef_L1
    L2_coef <- cov_coef_df$desired_coef_L2
    L3_coef <- cov_coef_df$desired_coef_L3

    pre_data <- defData(pre_data, varname = "L1_coef", formula = L1_coef)
    pre_data <- defData(pre_data, varname = "L2_coef", formula = L2_coef)
    pre_data <- defData(pre_data, varname = "L3_coef", formula = L3_coef)
  
    pre_data <- defData(pre_data, varname = "A", 
                        formula = "-1.815 + L1_coef*L1 + L2_coef*L2 + L3_coef*L3", 
                    dist = "binary", link = "logit")
    
    pre_data <- defData(pre_data, varname = "Y", 
                        formula = "0.437 + 0.767*A + 1.39*L2 -0.7*L3" , 
                    dist = "binary", link = "logit")
    
    df[[i]] <- genData(size, pre_data)
    }
  return(df)
}

no_boot_list <- generate_no_boot_data(1)
```


## Implementing nearest-neighbor matching (NNM)

```{r, warning=FALSE}
df <- no_boot_list

# could possible turn this into a function later.
matched_df <- list()

for (i in 1:length(df)) {
  
  matched <- matchit(A ~ L1 + L2 + L3, 
                          data = df[[i]], 
                          distance = "glm", 
                          link = "logit",
                          method = "nearest", 
                          ratio = 1) # perform NNM
  
  matched_df[[i]] <- match.data(matched, distance = "ps")
}
```


## simple Bootstrap

```{r}
# creating the tibble to apply map function
matched_tib <-
  tibble(data = matched_df)

# ### function to iterate glm over a list, to be used in purr:map ###
# returns tibble of parameter estimates and standard errors.

outcome_model_list <- function(list) {
  tib_coef <- tibble()
  pb3$tick()
  for (i in 1:length(list)) {
    mod <- glm(Y ~ A + ps, 
               data = list[[i]], 
               weights = weights, 
               family = "binomial") %>% summary()
    coefs <- mod$coefficients[2,1:2]
    tib_coef <- bind_rows(tib_coef, tibble(estimate = coefs[1], se = coefs[2]))
  }
    return(tib_coef)
}

# ### input matched dataframe, output however many bootstrapped samples you want ###
# first, set seed vector for reproducibility


# now, define function

seed_vec_2 <- rnorm(100000, mean = 0, sd = 10000) %>% round(0) %>% unique()

simple_boot <- function(df, n, size = 500, seeds = seed_vec_2){
  boots <- list()
  pb2$tick()
  for (i in 1:n) {
  set.seed(seeds[i])
  boots[[i]] <- 
    df %>% 
    filter(subclass %in% sample(levels(subclass), 
                                size, 
                                replace =  TRUE))
  }
  return(boots)
}


# adding progress bars for sanity
pb2 <- progress_bar$new(format = "bootstrapping... [:bar]", total = nrow(matched_tib))
pb3 <- progress_bar$new(format = "performing glm... [:bar]", total = nrow(matched_tib))

# creating booted tibbles, applying functions through purr:map.
boot_tib <- 
  matched_tib %>% 
  mutate(
    boots = map(.x = data, ~simple_boot(.x, n = 5))
    ) %>%
  mutate(coef = map(.x = boots, ~outcome_model_list(.x)))

```

```{r}
boot_estimates <- 
  boot_tib %>% 
  mutate(seq = seq(1:nrow(boot_tib))) %>% 
  select(coef, seq) %>% unnest(coef)
```

