---
title: "PS Bootstrap Binary Standardization"
author: "Hun"
date: "2/9/2022"
output: pdf_document
---


```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(simstudy)
library(MatchIt)
library(dplyr)
```

## Generating data with true log odds ratio and its standard deviation
```{r}
pre_data <- defData(varname = "L1", formula = "0", variance = 1,
                dist = "normal")
pre_data <- defData(pre_data, varname = "L2", formula = "0", variance = 1,
                dist = "normal")
pre_data <- defData(pre_data, varname = "L3", formula = "0", variance = 1,
                dist = "normal")
pre_data <- defData(pre_data, varname = "A", 
                    formula = " 0.5*L1 + 0.27*L2 -0.17*L3", 
                dist = "binary", link = "logit")
pre_data <- defData(pre_data, varname = "Y0", 
                    formula = "-1.5 + 1.77*L2 - 0.3*L3", 
                dist = "binary", link = "logit")
pre_data <- defData(pre_data, varname = "Y1", 
                    formula = "-0.7 + 1.77*L2 + 0.7*L3", 
                dist = "binary", link = "logit")
pre_data <- defData(pre_data, varname = "Y", 
                    formula = "0.5*A + 0.8*L2 + -0.1*L3", 
                dist = "binary", link = "logit")

set.seed(369)
df <- genData(1000, pre_data)
odds <- function(p) {
    return((p/(1 - p)))
}

sd_log_odds <- function(p1, p2, n1, n2){
  return(sqrt(1/(n1*p1) + 1/(n1*(1-p1)) + 1/(n2*p2) + 1/(n2*(1-p2))))
}

log(odds(mean(df$Y1)) / odds(mean(df$Y0)))

sd_log_odds(mean(df$Y1), mean(df$Y0), 1000, 1000)

mean(df$Y1-df$Y0)

sd(df$Y1-df$Y0)
```

## Propensity Score Model
```{r, echo = FALSE, warning = FALSE}
exposureModel <- glm(A ~ L1 + L2 + L3, data = df, family = "binomial")
#Note that Pr[A=0|L] = 1-Pr[A=1|L]

df.obs <-
  ifelse(df$A == 0,
         1 - predict(exposureModel, type = "response"),
         predict(exposureModel, type = "response"))

df_with_weight <-
  df %>%
  mutate(w = 1/df.obs, #inverse propensity score (weight)
         ps = df.obs) #propensity score

df$ps <- predict(exposureModel, df, type="response")
```

## 500 pairs Propensity Score distribution
```{r}
df %>%
  mutate(ps.grp = round(ps/0.05) * 0.05) %>%
  group_by(A, ps.grp) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(n2 = ifelse(A == 0, yes = n, no =  -1*n)) %>%
  ggplot(aes(x = ps.grp, y = n2, fill = as.factor(A))) +
  geom_bar(stat = 'identity', position = 'identity') +
  geom_text(aes(label = n, x = ps.grp, y = n2 + ifelse(A == 0, 8, -8))) +
  xlab('Probability of Quitting Smoking During Follow-up') +
  ylab('N') +
  ggtitle('Propensity Score Distribution by Treatment Group') +
  scale_fill_discrete('') +
  scale_x_continuous(breaks = seq(0, 1, 0.05)) +
  theme(legend.position = 'bottom', legend.direction = 'vertical',
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```

## Logit Outcome Model
```{r, warning = FALSE}
msm.w <- glm(Y ~ A , data = df_with_weight, family = "binomial", weights = w)

summary(msm.w)
```

## Nearest neighbor propensity score matching
```{r, warning = FALSE}
matched <- matchit(A ~ L1 + L2 + L3, data = df, 
                     distance = "glm", link = "logit",
                     method = "nearest", ratio = 1)

```


```{r, warning = FALSE}
summary(matched)[2]

plot(matched, type = "jitter", interactive = FALSE)

plot(matched, type = "histogram")
```

```{r}
matched_df <- 
  match.data(matched)
```

## 495 pairs propensity score distribution
```{r}
matched_df %>%
  mutate(ps.grp = round(ps/0.05) * 0.05) %>%
  group_by(A, ps.grp) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(n2 = ifelse(A == 0, yes = n, no =  -1*n)) %>%
  ggplot(aes(x = ps.grp, y = n2, fill = as.factor(A))) +
  geom_bar(stat = 'identity', position = 'identity') +
  geom_text(aes(label = n, x = ps.grp, y = n2 + ifelse(A == 0, 8, -8))) +
  xlab('Probability of Quitting Smoking During Follow-up') +
  ylab('N') +
  ggtitle('Propensity Score Distribution by Treatment Group') +
  scale_fill_discrete('') +
  scale_x_continuous(breaks = seq(0, 1, 0.05)) +
  theme(legend.position = 'bottom', legend.direction = 'vertical',
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```


## simple bootstrap
```{r}

nboot <- 100
# set up a matrix to store results
boots <- data.frame(i = 1:nboot,
                    se_OR = NA,
                    mean_log_OR = NA,
                    mean1 = NA,
                    mean0 = NA,
                    difference = NA
                    )
# loop to perform the bootstrapping
  
for(i in 1:nboot) {
  # sample with replacement
  sampl <- matched_df %>% filter(subclass %in% sample(levels(subclass),494, replace =  TRUE))
  
  bootmod <- glm(Y ~ A + ps, data = sampl, 
                 weights = weights, family = binomial)
  
  # create new data sets
  sampl.treated <- sampl %>%
    mutate(A = 1)
  
  sampl.untreated <- sampl %>%
    mutate(A = 0)
  
  # predict values
  sampl.treated$pred.y <- 
    predict(bootmod, sampl.treated, type = "response")
  
  sampl.untreated$pred.y <- 
    predict(bootmod, sampl.untreated, type = "response")
  
   # output results
  
  boots[i, "mean_log_OR"] <- summary(bootmod)$coeff[2,1]
  
  boots[i, "se_OR"] <- summary(bootmod)$coeff[2,2]
  
  boots[i, "mean1"] <- mean(sampl.treated$pred.y)
  boots[i, "mean0"] <- mean(sampl.untreated$pred.y)
  boots[i, "difference"] <- boots[i, "mean1"] - boots[i, "mean0"]
  
  se_ATE <- sd(boots$difference)

  ATE <- mean(boots$difference)
  
  # once loop is done, print the results
  if (i == nboot){
    cat("ATE:")
    cat(ATE)
    cat("\n")
    cat("\n")
    cat("se_ATE:")
    cat(se_ATE)
    cat("\n")
    cat("\n")
    cat("95% CI for ATE:")
    cat(ATE - 1.96*se_ATE, 
        ",",
        ATE + 1.96*se_ATE)
    cat("\n")
    cat("\n")
    cat("log OR:")
    cat(mean(boots$mean_log_OR))
    cat("\n")
    cat("\n")
    cat("se_OR:")
    cat(mean(boots$se_OR))
    cat("\n")
    cat("\n")
    cat("95% CI for log odds ratio:")
    cat(mean(boots$mean_log_OR) - 1.96*mean(boots$se_OR), 
        ",",
        mean(boots$mean_log_OR) + 1.96*mean(boots$se_OR))
  }
}

```

```{r}
hist(boots$mean_log_OR)

hist(boots$se_OR)
```








