---
title: "PS Bootstrap Continuous Outcome"
author: "Hun"
date: "2/7/2022"
output: pdf_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
library(simstudy)
library(MatchIt)
library(dplyr)
```

## Generating data with true log odds ratio and its standard deviation
```{r}
pre_data <- defData(varname = "L1", formula = "0", variance = 1,
                dist = "normal")
pre_data <- defData(pre_data, varname = "L2", formula = "0", variance = 1,
                dist = "normal")
pre_data <- defData(pre_data, varname = "L3", formula = "0", variance = 1,
                dist = "normal")
pre_data <- defData(pre_data, varname = "A", 
                    formula = " 0.5*L1 + 0.27*L2 -0.17*L3", 
                dist = "binary", link = "logit")
pre_data <- defData(pre_data, varname = "Y", 
                    formula = "2 + 1.5*A + 0.8*L2 + -0.1*L3", 
                dist = "nonrandom")

set.seed(7777)
df <- genData(1000, pre_data)

# TRUE ATE: 1.5
```

## Propensity Score Model
```{r, echo = FALSE, warning = FALSE}
exposureModel <- glm(A ~ L1 + L2 + L3, data = df, family = "binomial")
#Note that Pr[A=0|L] = 1-Pr[A=1|L]


df$ps <- predict(exposureModel, df, type="response") #getting estimated propensity score
```

## 500 pairs Propensity Score distribution
```{r}
df %>%
  mutate(ps.grp = round(ps/0.05) * 0.05) %>%
  group_by(A, ps.grp) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(n2 = ifelse(A == 0, yes = n, no =  -1*n)) %>%
  ggplot(aes(x = ps.grp, y = n2, fill = as.factor(A))) +
  geom_bar(stat = 'identity', position = 'identity') +
  geom_text(aes(label = n, x = ps.grp, y = n2 + ifelse(A == 0, 8, -8))) +
  xlab('Probability of Quitting Smoking During Follow-up') +
  ylab('N') +
  ggtitle('Propensity Score Distribution by Treatment Group') +
  scale_fill_discrete('') +
  scale_x_continuous(breaks = seq(0, 1, 0.05)) +
  theme(legend.position = 'bottom', legend.direction = 'vertical',
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```


## Nearest neighbor propensity score matching
```{r, warning = FALSE}
matched <- matchit(A ~ L1 + L2 + L3, data = df, 
                     distance = "glm", link = "logit",
                     method = "nearest", ratio = 1)

```


```{r, warning = FALSE}
summary(matched)[2]

plot(matched, type = "jitter", interactive = FALSE)

plot(matched, type = "histogram")
```

```{r}
matched_df <- 
  match.data(matched)
```

## 495 pairs propensity score distribution
```{r}
matched_df %>%
  mutate(ps.grp = round(ps/0.05) * 0.05) %>%
  group_by(A, ps.grp) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  mutate(n2 = ifelse(A == 0, yes = n, no =  -1*n)) %>%
  ggplot(aes(x = ps.grp, y = n2, fill = as.factor(A))) +
  geom_bar(stat = 'identity', position = 'identity') +
  geom_text(aes(label = n, x = ps.grp, y = n2 + ifelse(A == 0, 8, -8))) +
  xlab('Probability of Quitting Smoking During Follow-up') +
  ylab('N') +
  ggtitle('Propensity Score Distribution by Treatment Group') +
  scale_fill_discrete('') +
  scale_x_continuous(breaks = seq(0, 1, 0.05)) +
  theme(legend.position = 'bottom', legend.direction = 'vertical',
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```


## simple bootstrap
```{r}

nboot <- 100
# set up a matrix to store results
boots <- data.frame(i = 1:nboot,
                    se = NA,
                    mean1 = NA,
                    mean0 = NA,
                    beta1 = NA, 
                    ATE = NA
                    )
# loop to perform the bootstrapping
  
for(i in 1:nboot) {
  # sample with replacement
  sampl <- matched_df %>% filter(subclass %in% sample(levels(subclass),500, replace =  TRUE))
  
  bootmod <- glm(Y ~ A + ps, data = sampl, 
                 weights = weights)
  
  # create new data sets
  sampl.treated <- sampl %>%
    mutate(A = 1)
  
  sampl.untreated <- sampl %>%
    mutate(A = 0)
  
  # predict values
  sampl.treated$pred.y <- 
    predict(bootmod, sampl.treated)
  
  sampl.untreated$pred.y <- 
    predict(bootmod, sampl.untreated)
  
   # output results
  
  boots[i, "beta1"] <- summary(bootmod)$coeff[2,1]
  boots[i, "se"] <- summary(bootmod)$coeff[2,2]
  boots[i, "mean1"] <- mean(sampl.treated$pred.y)
  boots[i, "mean0"] <- mean(sampl.untreated$pred.y)
  boots[i, "ATE"] <- boots[i, "mean1"] - boots[i, "mean0"]
  
  Empirical_sd <- sd(boots$ATE)

  ATE <- mean(boots$ATE)
  
  mean_se <- mean(boots$se)
  
  # once loop is done, print the results
  if (i == nboot) {
    cat("ATE:")
    cat(ATE)
    cat("\n")
    cat("\n")
    cat("Empirical_sd:")
    cat(Empirical_sd)
    cat("\n")
    cat("\n")
    cat("mean_se:")
    cat(mean_se)
    cat("\n")
    cat("\n")
    cat("95% CI for ATE:")
    cat(ATE - 1.96*mean_se, 
        ",",
        ATE + 1.96*mean_se)
    cat("\n")
    cat("\n")
    cat("ATE from beta:") #checking if our computation is correct
    cat(mean(boots$beta1))

  }
}

```

```{r}
hist(boots$ATE)
hist(boots$se)
```









