---
title: "Plotting all the results"
author: "Amy Pitts"
date: "2/19/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```

Jimmy needs to give me the right esitamte of effect right now here is what I am using 
```{r setting true effects}
smaller_true_ATE <- 0.15
bigger_true_ATE <- 0.3

pos_beta <- 1
neg_beta <- -1
```

## Loading Data

```{r loading binary data, echo = FALSE}
load("./output_data/binary_scen_1.RData")
load("./output_data/binary_scen_2.RData")
load("./output_data/binary_scen_3.RData")
load("./output_data/binary_scen_4.RData")
load("./output_data/binary_scen_5.RData")
load("./output_data/binary_scen_6.RData")
load("./output_data/binary_scen_13.RData")
load("./output_data/binary_scen_14.RData")
load("./output_data/binary_scen_15.RData")
load("./output_data/binary_scen_16.RData")
load("./output_data/binary_scen_17.RData")
load("./output_data/binary_scen_18.RData")
```

```{r loading continuous data, echo = FALSE}
load("./output_data/cont_df_scen_1.RData")
load("./output_data/cont_df_scen_2.RData")
load("./output_data/cont_df_scen_3.RData")
load("./output_data/cont_df_scen_4.RData")
load("./output_data/cont_df_scen_5.RData")
load("./output_data/cont_df_scen_6.RData")
load("./output_data/cont_df_scen_13.RData")
load("./output_data/cont_df_scen_14.RData")
load("./output_data/cont_df_scen_15.RData")
load("./output_data/cont_df_scen_16.RData")
load("./output_data/cont_df_scen_17.RData")
load("./output_data/cont_df_scen_18.RData")
```

```{r creating all scenarios tables, echo = FALSE}
bin_all_scenarios <- tibble(
  id = c(1:18),
  n_sample = c(rep(1000, 6), rep(10000, 6), rep(100, 6)),
  desired_prop = rep(c(0.1, 0.1, 0.2, 0.2, 0.3, 0.3),3),
  beta1 = rep(c(0.767, 1.587),9),
  beta0 = rep(c(0.422, 0.873, 0.46, 0.952, 0.499, 1.032), 3)
)

cont_all_scenarios <- tibble(
  id = c(1:18),
  n_sample = c(rep(1000, 6), rep(10000, 6), rep(100, 6)),
  desired_prop = rep(c(0.1, 0.1, 0.2, 0.2, 0.3, 0.3),3),
  beta1 = rep(c(1, -1),9)
)
```

## Compiling Binary Data
Get all the odd numbers $\beta_1 = 0.767$
```{r compiling odd-numbered scenarios with smaller beta1}
binary_final_odd <- 
  binary_scen_1 %>% mutate(n_sample = 1000, beta1 = 0.767, desired_prop = 0.1) %>% 
  bind_rows(binary_scen_3 %>% mutate(n_sample = 1000, beta1 = 0.767, desired_prop = 0.2)) %>%
  bind_rows(binary_scen_5 %>% mutate(n_sample = 1000, beta1 = 0.767, desired_prop = 0.3)) %>%
  bind_rows(binary_scen_13 %>% mutate(n_sample = 100, beta1 = 0.767, desired_prop = 0.1)) %>%
  bind_rows(binary_scen_15 %>% mutate(n_sample = 100, beta1 = 0.767, desired_prop = 0.2)) %>%
  bind_rows(binary_scen_17 %>% mutate(n_sample = 100, beta1 = 0.767, desired_prop = 0.3))

binary_final_odd <- binary_final_odd %>% 
  mutate(
    ATE_bias = ATE - smaller_true_ATE,
    empirical_bias = empirical_mean - smaller_true_ATE,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 

rm(binary_scen_1, binary_scen_3, binary_scen_5, binary_scen_13, binary_scen_15, binary_scen_17)
```

Get all the even numbers $\beta_1 = 1.386$
```{r compiling even-numbered scenarios with larger beta1}
binary_final_even <- 
  binary_scen_2 %>% mutate(n_sample = 1000, beta1 = 1.386, desired_prop = 0.1) %>% 
  bind_rows(binary_scen_4 %>% mutate(n_sample = 1000, beta1 = 1.386, desired_prop = 0.2)) %>%
  bind_rows(binary_scen_6 %>% mutate(n_sample = 1000, beta1 = 1.386, desired_prop = 0.3)) %>%
  bind_rows(binary_scen_14 %>% mutate(n_sample = 100, beta1 = 1.386, desired_prop = 0.1)) %>%
  bind_rows(binary_scen_16 %>% mutate(n_sample = 100, beta1 = 1.386, desired_prop = 0.2)) %>%
  bind_rows(binary_scen_18 %>% mutate(n_sample = 100, beta1 = 1.386, desired_prop = 0.3))
 

binary_final_even <- binary_final_even %>% 
  mutate(
    ATE_bias = ATE - bigger_true_ATE,
    empirical_bias = empirical_mean - bigger_true_ATE,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 

rm(binary_scen_2, binary_scen_4, binary_scen_6, binary_scen_14, binary_scen_16, binary_scen_18)
```

```{r final binary data set}
binary_final <- binary_final_even %>% bind_rows(binary_final_odd)
```

## Compiling Continuous Data
```{r compiling odd-numbered scenarios}
continuous_final_odd <- 
  cont_df_scen_1 %>% mutate(n_sample = 1000, beta1 = pos_beta, desired_prop = 0.1) %>% 
  bind_rows(cont_df_scen_3 %>% mutate(n_sample = 1000, beta1 = pos_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_5 %>% mutate(n_sample = 1000, beta1 = pos_beta, desired_prop = 0.3)) %>% 
  bind_rows(cont_df_scen_13 %>% mutate(n_sample = 100, beta1 = pos_beta, desired_prop = 0.1)) %>% 
  bind_rows(cont_df_scen_15 %>% mutate(n_sample = 100, beta1 = pos_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_17 %>% mutate(n_sample = 100, beta1 = pos_beta, desired_prop = 0.3)) %>% 
  mutate(
    ATE_bias = ATE - pos_beta,
    empirical_bias = empirical_mean - pos_beta,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 

rm(cont_df_scen_1, cont_df_scen_3, cont_df_scen_5, cont_df_scen_13, cont_df_scen_15, cont_df_scen_17)
```

```{r compiling even-numbered scenarios}
continuous_final_even <- 
  cont_df_scen_2 %>% mutate(n_sample = 1000, beta1 = neg_beta, desired_prop = 0.1) %>% 
  bind_rows(cont_df_scen_4 %>% mutate(n_sample = 1000, beta1 = neg_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_6 %>% mutate(n_sample = 1000, beta1 = neg_beta, desired_prop = 0.3)) %>% 
  bind_rows(cont_df_scen_14 %>% mutate(n_sample = 100, beta1 = neg_beta, desired_prop = 0.1)) %>% 
  bind_rows(cont_df_scen_16 %>% mutate(n_sample = 100, beta1 = neg_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_18 %>% mutate(n_sample = 100, beta1 = neg_beta, desired_prop = 0.3)) %>% 
  mutate(
    ATE_bias = ATE - neg_beta,
    empirical_bias = empirical_mean - neg_beta,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 

rm(cont_df_scen_2, cont_df_scen_4, cont_df_scen_6, cont_df_scen_14, cont_df_scen_16, cont_df_scen_18)
```

```{r final continuous data set}
continuous_final <-
  continuous_final_odd %>%
  bind_rows(continuous_final_even)

rm(continuous_final_even, continuous_final_odd)
```


## Binary Coverage Rates
```{r calculating coverage rate for binary data, echo = FALSE}
cr_df<- binary_final %>%
  mutate(scenario = factor(scenario),
         new_name = str_c("sample = ", n_sample, ", treat prop = ", desired_prop),
         treat_effect = ifelse(beta1 == 0.767, "True ATE = 0.15", "True ATE = 0.3")) %>%  
  group_by( new_name, treat_effect, boot_type ) %>%
  summarize(cr = sum(covered)/ 100) 
```

name the scenarios by sample size and treat prop and facet by the treatment effect 

```{r plotting coverage rates for binary data}
ggplot(cr_df, aes(x=cr, y=new_name, color=boot_type)) + 
  geom_point(position=position_dodge(0.3))+
  geom_vline(xintercept=0.9927, linetype="dashed", color = "black") +
   geom_vline(xintercept=0.9072, linetype="dashed", color = "black") +
   geom_vline(xintercept=0.95, linetype="dashed", color = "black") +
  facet_grid(~treat_effect) + 
  labs(
   title = "Binary Coverage Rates by Parameters of Interest", 
   y = "Scenario",
   x = "CI Coverage Rate"
  )+theme_bw()
```

## Continuous Coverage Rates
```{r calculating coverage rate for continuous data, echo = FALSE}
cr_df_cont <- 
  continuous_final %>%
  mutate(scenario = factor(scenario_id),
         new_name = str_c("sample = ", n_sample, ", treat prop = ", desired_prop),
         treat_effect = ifelse(beta1 == pos_beta, "True ATE = 1", "True ATE = -1")) %>%  
  group_by(new_name, treat_effect, boot_type) %>%
  summarize(cr = sum(covered)/ 100) 
```

```{r plotting coverage rates for continuous data}
ggplot(cr_df_cont, aes(x=cr, y=new_name, color=boot_type)) + 
  geom_point(position=position_dodge(0.3))+
  geom_vline(xintercept=0.9927, linetype="dashed", color = "black") +
   geom_vline(xintercept=0.9072, linetype="dashed", color = "black") +
   geom_vline(xintercept=0.95, linetype="dashed", color = "black") +
  facet_grid(~treat_effect) + 
  labs(
   title = "Continuous Coverage Rates by Parameters of Interest", 
   y = "Scenario",
   x = "CI Coverage Rate"
  )+theme_bw()
```

Bias 
```{r calculating and plotting bias for binary data, echo = FALSE}
empirical_data <- binary_final %>%
  mutate(
    scenario = factor(scenario),
    new_name = str_c("sample = ", n_sample, ", treat prop = ", desired_prop),
    treat_effect = ifelse(beta1 == 0.767, "True ATE = 0.15", "True ATE = 0.3")
  ) %>% 
  select(scenario, new_name, treat_effect, empirical_bias, empirical_se) %>%
  unique() %>% 
  rename(
    ATE_bias  = empirical_bias,
    bias_se = empirical_se
  ) %>%
  mutate(
    Method = "Empirical"
  )

boot_data <- binary_final %>%
  mutate(scenario = factor(scenario),
         new_name = str_c("sample = ", n_sample, ", treat prop = ", desired_prop),
         treat_effect = ifelse(beta1 == 0.767, "True ATE = 0.15", "True ATE = 0.3"),
         Method = boot_type
         ) %>% 
  group_by(Method, scenario, new_name, treat_effect ) %>%
  summarize(
    ATE_bias = mean(ATE_bias),
    bias_se = mean(sd_ATE)
  ) 

bind_rows(boot_data,empirical_data ) %>%
  mutate(
    Method = factor(Method, levels = c("Empirical", "Simple", "Complex"))
  ) %>% 
  ggplot( aes(x=ATE_bias, y=new_name, color=Method)) + 
    geom_point(position=position_dodge(0.3))+
    geom_errorbar(aes(xmin=ATE_bias-1.96*bias_se, xmax=ATE_bias+1.96*bias_se), width=.2,
                 position=position_dodge(0.3)) +
    geom_vline(xintercept=0, linetype="dashed", color = "black") +
    facet_grid(~treat_effect) +
    labs(
     title = "Binary Simulation Bias and Standard Error CI", 
     y = "Scenario",
     x = "Bias"
    )+theme_bw()
```

```{r calculating and plotting bias for continuous data, echo = FALSE}
empirical_data_cont <- 
  continuous_final %>%
  mutate(
    scenario = factor(scenario_id),
    new_name = str_c("sample = ", n_sample, ", treat prop = ", desired_prop),
    treat_effect = ifelse(beta1 == pos_beta, "True ATE = 1", "True ATE = -1")
  ) %>% 
  select(scenario, new_name, treat_effect, empirical_bias, empirical_se) %>%
  unique() %>% 
  rename(
    ATE_bias  = empirical_bias,
    bias_se = empirical_se
  ) %>%
  mutate(
    Method = "Empirical"
  )

boot_data_cont <- 
  continuous_final %>%
  mutate(scenario = factor(scenario_id),
         new_name = str_c("sample = ", n_sample, ", treat prop = ", desired_prop),
         treat_effect = ifelse(beta1 == pos_beta, "True ATE = 1", "True ATE = -1"),
         Method = factor(boot_type)
         ) %>% 
  group_by(Method, scenario, new_name, treat_effect ) %>%
  summarize(
    ATE_bias = mean(ATE_bias),
    bias_se = mean(sd_ATE)
  ) 

bind_rows(boot_data_cont, empirical_data_cont) %>%
  mutate(
    Method = factor(Method, levels = c("Empirical", "Simple", "Complex"))
  ) %>% 
  ggplot(aes(x=ATE_bias, y=new_name, color=Method)) + 
    geom_point(position=position_dodge(0.3))+
    geom_errorbar(aes(xmin=ATE_bias-1.96*bias_se, xmax=ATE_bias+1.96*bias_se), width=.2,
                 position=position_dodge(0.3)) +
    geom_vline(xintercept=0, linetype="dashed", color = "black") +
    facet_grid(~treat_effect) +
    labs(
     title = "Continuous Simulation Bias and Standard Error CI", 
     y = "Scenario",
     x = "Bias"
    )+theme_bw()
```

## Standard Error 
```{r calculating and plotting standard error for binary data, echo = FALSE}
bind_rows(boot_data,empirical_data ) %>%
  mutate(
    Method = factor(Method, levels = c("Empirical", "Simple", "Complex"))
  ) %>% 
  ggplot( aes(x=bias_se, y=new_name, color=Method)) + 
    geom_point(position=position_dodge(0.3))+
    facet_grid(~treat_effect) +
    labs(
     title = "Binary Simulation Standard Error", 
     y = "Scenario",
     x = "Standard Error"
    )+theme_bw()
```

```{r calculating and plotting standard error for continuous data, echo = FALSE}
bind_rows(boot_data_cont, empirical_data_cont) %>%
  mutate(
    Method = factor(Method, levels = c("Empirical", "Simple", "Complex"))
  ) %>% 
  ggplot(aes(x=bias_se, y=new_name, color=Method)) + 
    geom_point(position=position_dodge(0.3))+
    facet_grid(~treat_effect) +
    labs(
     title = "Continuous Simulation Standard Error", 
     y = "Scenario",
     x = "Standard Error"
    )+theme_bw()
```

