---
title: "Result Graph Summary"
author: "Hun"
date: "2/19/2022"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(kableExtra)
```

Jimmy needs to give me the right esitmate of effect right now here is what I am using 
```{r setting true effects}
smaller_true_ATE <- 0.15
bigger_true_ATE <- 0.3

pos_beta <- 1
neg_beta <- -1
```

```{r loading binary data, echo = FALSE}
load("./new_output_data/binary_scen_1.RData")
load("./new_output_data/binary_scen_2.RData")
load("./new_output_data/binary_scen_3.RData")
load("./new_output_data/binary_scen_4.RData")
load("./new_output_data/binary_scen_5.RData")
load("./new_output_data/binary_scen_6.RData")
load("./new_output_data/binary_scen_13.RData")
load("./new_output_data/binary_scen_14.RData")
load("./new_output_data/binary_scen_15.RData")
load("./new_output_data/binary_scen_16.RData")
load("./new_output_data/binary_scen_17.RData")
load("./new_output_data/binary_scen_18.RData")
```

```{r loading continuous data, echo = FALSE}
load("./output_data/cont_df_scen_1.RData")
load("./output_data/cont_df_scen_2.RData")
load("./output_data/cont_df_scen_3.RData")
load("./output_data/cont_df_scen_4.RData")
load("./output_data/cont_df_scen_5.RData")
load("./output_data/cont_df_scen_6.RData")
load("./output_data/cont_df_scen_13.RData")
load("./output_data/cont_df_scen_14.RData")
load("./output_data/cont_df_scen_15.RData")
load("./output_data/cont_df_scen_16.RData")
load("./output_data/cont_df_scen_17.RData")
load("./output_data/cont_df_scen_18.RData")
```

```{r, eval = FALSE}
view(binary_scen_1)
```

```{r creating all scenarios tables, echo = FALSE}
bin_all_scenarios <- tibble(
  id = c(1:18),
  n_sample = c(rep(1000, 6), rep(10000, 6), rep(100, 6)),
  desired_prop = rep(c(0.1, 0.1, 0.2, 0.2, 0.3, 0.3),3),
  beta1 = rep(c(0.767, 1.587),9),
  beta0 = rep(c(0.422, 0.873, 0.46, 0.952, 0.499, 1.032), 3)
)

cont_all_scenarios <- tibble(
  id = c(1:18),
  n_sample = c(rep(1000, 6), rep(10000, 6), rep(100, 6)),
  desired_prop = rep(c(0.1, 0.1, 0.2, 0.2, 0.3, 0.3),3),
  beta1 = rep(c(1, -1),9)
)
```

## Compiling Binary Data
Get all the odd numbers $\beta_1 = 0.767$
```{r compiling odd-numbered scenarios with smaller beta1}
binary_final_odd <- 
  binary_scen_1 %>% mutate(n_sample = 1000, beta1 = 0.767, desired_prop = 0.1) %>% 
  bind_rows(binary_scen_3 %>% mutate(n_sample = 1000, beta1 = 0.767, desired_prop = 0.2)) %>%
  bind_rows(binary_scen_5 %>% mutate(n_sample = 1000, beta1 = 0.767, desired_prop = 0.3)) %>%
  bind_rows(binary_scen_13 %>% mutate(n_sample = 100, beta1 = 0.767, desired_prop = 0.1)) %>%
  bind_rows(binary_scen_15 %>% mutate(n_sample = 100, beta1 = 0.767, desired_prop = 0.2)) %>%
  bind_rows(binary_scen_17 %>% mutate(n_sample = 100, beta1 = 0.767, desired_prop = 0.3))

binary_final_odd <- binary_final_odd %>% 
  mutate(
    ATE_bias = ATE - smaller_true_ATE,
    E_Bias = empirical_mean - smaller_true_ATE,
    E_SE = empirical_se,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 



rm(binary_scen_1, binary_scen_3, binary_scen_5, binary_scen_13, binary_scen_15, binary_scen_17)
```


Get all the even numbers $\beta_1 = 1.386$
```{r compiling even-numbered scenarios with larger beta1}
binary_final_even <- 
  binary_scen_2 %>% mutate(n_sample = 1000, beta1 = 1.386, desired_prop = 0.1) %>% 
  bind_rows(binary_scen_4 %>% mutate(n_sample = 1000, beta1 = 1.386, desired_prop = 0.2)) %>%
 bind_rows(binary_scen_6 %>% mutate(n_sample = 1000, beta1 = 1.386, desired_prop = 0.3)) %>%
 bind_rows(binary_scen_14 %>% mutate(n_sample = 100, beta1 = 1.386, desired_prop = 0.1)) %>%
 bind_rows(binary_scen_16 %>% mutate(n_sample = 100, beta1 = 1.386, desired_prop = 0.2)) %>%
 bind_rows(binary_scen_18 %>% mutate(n_sample = 100, beta1 = 1.386, desired_prop = 0.3))

binary_final_even <- binary_final_even %>% 
  mutate(
    ATE_bias = ATE - bigger_true_ATE,
    E_Bias = empirical_mean - bigger_true_ATE,
    E_SE = empirical_se,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 

rm(binary_scen_2, binary_scen_4, binary_scen_6, binary_scen_14, binary_scen_16, binary_scen_18)
```

```{r final binary data set}
binary_final <- binary_final_even %>% bind_rows(binary_final_odd)
```


## Compiling Continuous Data
```{r compiling odd-numbered scenarios}
continuous_final_odd <- 
  cont_df_scen_1 %>% mutate(n_sample = 1000, beta1 = pos_beta, desired_prop = 0.1) %>% 
  bind_rows(cont_df_scen_3 %>% mutate(n_sample = 1000, beta1 = pos_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_5 %>% mutate(n_sample = 1000, beta1 = pos_beta, desired_prop = 0.3)) %>% 
  bind_rows(cont_df_scen_13 %>% mutate(n_sample = 100, beta1 = pos_beta, desired_prop = 0.1)) %>% 
  bind_rows(cont_df_scen_15 %>% mutate(n_sample = 100, beta1 = pos_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_17 %>% mutate(n_sample = 100, beta1 = pos_beta, desired_prop = 0.3)) %>% 
  mutate(
    ATE_bias = ATE - pos_beta,
    E_Bias = empirical_mean - pos_beta,
    E_SE = empirical_se,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 

rm(cont_df_scen_1, cont_df_scen_3, cont_df_scen_5, cont_df_scen_13, cont_df_scen_15, cont_df_scen_17)
```

```{r compiling even-numbered scenarios}
continuous_final_even <- 
  cont_df_scen_2 %>% mutate(n_sample = 1000, beta1 = neg_beta, desired_prop = 0.1) %>% 
  bind_rows(cont_df_scen_4 %>% mutate(n_sample = 1000, beta1 = neg_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_6 %>% mutate(n_sample = 1000, beta1 = neg_beta, desired_prop = 0.3)) %>% 
  bind_rows(cont_df_scen_14 %>% mutate(n_sample = 100, beta1 = neg_beta, desired_prop = 0.1)) %>% 
  bind_rows(cont_df_scen_16 %>% mutate(n_sample = 100, beta1 = neg_beta, desired_prop = 0.2)) %>% 
  bind_rows(cont_df_scen_18 %>% mutate(n_sample = 100, beta1 = neg_beta, desired_prop = 0.3)) %>% 
  mutate(
    ATE_bias = ATE - neg_beta,
    E_Bias = empirical_mean - neg_beta,
    E_SE = empirical_se,
    boot_type = ifelse(boot_type == 0, "Simple", "Complex")
  ) 

rm(cont_df_scen_2, cont_df_scen_4, cont_df_scen_6, cont_df_scen_14, cont_df_scen_16, cont_df_scen_18)
```

```{r final continuous data set}
continuous_final <-
  continuous_final_odd %>%
  bind_rows(continuous_final_even) %>% 
  rename(scenario = scenario_id)

rm(continuous_final_even, continuous_final_odd)
```

## Creating Dataframes
```{r coverage rate dataframes, message=FALSE}
cr_df_binary <-
  binary_final %>%
  group_by(scenario, boot_type) %>%
  summarize(cr = (sum(covered) / 100) %>% round(digits = 3)) %>%
  pivot_wider(names_from = boot_type, values_from = cr) %>% 
  rename(S_CR = Simple, C_CR = Complex)

cr_df_continuous <-
  continuous_final %>%
  group_by(scenario, boot_type) %>%
  summarize(cr = (sum(covered) / 100) %>% round(digits = 3)) %>%
  pivot_wider(names_from = boot_type, values_from = cr) %>% 
  rename(S_CR = Simple, C_CR = Complex)
```

```{r standard error dataframes, message=FALSE}
se_df_binary <-
  binary_final %>%
  group_by(scenario, boot_type) %>%
  summarize(se_ATE = sd(ATE) %>% round(digits = 3)) %>%
  pivot_wider(names_from = boot_type, values_from = se_ATE) %>% 
  rename(S_SE = Simple, C_SE = Complex)

se_df_continuous <-
  continuous_final %>%
  group_by(scenario, boot_type) %>%
  summarize(se_ATE = sd(ATE) %>% round(digits = 3)) %>%
  pivot_wider(names_from = boot_type, values_from = se_ATE) %>% 
  rename(S_SE = Simple, C_SE = Complex)
```

```{r bias dataframes, message=FALSE}
bias_df_binary <-
  binary_final %>%
  group_by(scenario, boot_type) %>%
  summarize(bias = mean(ATE_bias) %>% round(digits = 3)) %>%
  pivot_wider(names_from = boot_type, values_from = bias) %>% 
  rename(S_Bias = Simple, C_Bias = Complex)

bias_df_continuous <-
  continuous_final %>%
  group_by(scenario, boot_type) %>%
  summarize(bias = mean(ATE_bias) %>% round(digits = 3)) %>%
  pivot_wider(names_from = boot_type, values_from = bias) %>% 
  rename(S_Bias = Simple, C_Bias = Complex)
```

## Adding Empirical



```{r}
E_df <-
  binary_final %>% 
  group_by(scenario) %>% 
  summarise(E_SE = mean(E_SE) %>% round(digits = 3) , 
            E_Bias = mean(E_Bias) %>% round(digits = 3))

E_df <-
  continuous_final %>% 
  group_by(scenario) %>% 
  summarise(E_SE = mean(E_SE) %>% round(digits = 3) , 
            E_Bias = mean(E_Bias) %>% round(digits = 3))
```


```{r final result dataframes, message=FALSE}
all_result_binary <-
  se_df_binary %>% 
  full_join(bias_df_binary) %>% 
  full_join(cr_df_binary) %>% 
  full_join(E_df) %>%
  relocate(starts_with("S")) %>% 
  relocate(starts_with("E")) %>%
  relocate(scenario) %>%
  rename(Scenario = scenario)
 
all_result_continuous <-
  se_df_continuous %>% 
  full_join(bias_df_continuous) %>% 
  full_join(cr_df_continuous) %>% 
  full_join(E_df) %>%
  relocate(starts_with("S")) %>% 
  relocate(starts_with("E")) %>%
  relocate(scenario) %>%
  rename(Scenario = scenario)

all_result_binary 

all_result_continuous
```

```{r labeling scenarios}
all_result_continuous["Scenario"] <- 
                          c("Large Sample, ATE = +1, p = 0.1", 
                            "Large Sample, ATE = -1, p = 0.1",
                            "Large Sample, ATE = +1, p = 0.2",
                            "Large Sample, ATE = -1, p = 0.2",
                            "Large Sample, ATE = +1, p = 0.3",
                            "Large Sample, ATE = -1, p = 0.3",
                            "Small Sample, ATE = +1, p = 0.1",
                            "Small Sample, ATE = -1, p = 0.1",
                            "Small Sample, ATE = +1, p = 0.2",
                            "Small Sample, ATE = -1, p = 0.2",
                            "Small Sample, ATE = +1, p = 0.3",
                            "Small Sample, ATE = -1, p = 0.3")

all_result_continuous <- all_result_continuous[c(1,3,5,2,4,6,7,9,11,8,10,12),]


all_result_binary["Scenario"] <- 
                          c("Large Sample, ATE = 0.15, p = 0.1", 
                            "Large Sample, ATE = 0.30, p = 0.1",
                            "Large Sample, ATE = 0.15, p = 0.2",
                            "Large Sample, ATE = 0.30, p = 0.2",
                            "Large Sample, ATE = 0.15, p = 0.3",
                            "Large Sample, ATE = 0.30, p = 0.3",
                            "Small Sample, ATE = 0.15, p = 0.1",
                            "Small Sample, ATE = 0.30, p = 0.1",
                            "Small Sample, ATE = 0.15, p = 0.2",
                            "Small Sample, ATE = 0.30, p = 0.2",
                            "Small Sample, ATE = 0.15, p = 0.3",
                            "Small Sample, ATE = 0.30, p = 0.3")

all_result_binary <- all_result_binary[c(1,3,5,2,4,6,7,9,11,8,10,12),]

```

```{r displaying results}
all_result_binary %>%
  kbl(caption = "Table 1: Binary outcome summary") %>%
  kable_classic("striped", full_width = F , html_font = "Cambria") %>%
  column_spec(2, width = "2cm")  %>%
  column_spec(1:9, border_left = T, border_right = T) %>%
  add_header_above(c("Binary Outcome" = 0, "Empirical" = 3, "Simple" = 1, "Complex" = 5)) %>%
  row_spec(1:3, bold = T, color = "black", background = "lightgrey") %>%
  row_spec(4:6, bold = T, color = "black", background = "white") %>%
  row_spec(7:9, bold = T, color = "black", background = "lightgrey") %>%
  row_spec(10:12, bold = T, color = "black", background = "white")
```

```{r displaying results}
all_result_continuous %>%
  kbl(caption = "Table 2: Continuous outcome summary") %>%
  kable_classic("striped", full_width = F , html_font = "Cambria") %>%
  column_spec(2, width = "2cm")  %>%
  column_spec(1:9, border_left = T, border_right = T) %>%
  add_header_above(c("Continuous Outcome" = 0, "Empirical" = 3, 
                     "Simple" = 1, "Complex" = 5)) %>%
  row_spec(1:3, bold = T, color = "black", background = "lightgrey") %>%
  row_spec(4:6, bold = T, color = "black", background = "white") %>%
  row_spec(7:9, bold = T, color = "black", background = "lightgrey") %>%
  row_spec(10:12, bold = T, color = "black", background = "white")
```


