---
title: "Complex Bootstrap Binary (V2)"
author: "Waveley Qiu"
date: "2022-02-16"
output: pdf_document
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
source('./shared_code/setup.R')
```

## Generating Data

```{r}
source('./shared_code/data_gen_final_pretty.R')
```

## Complex Bootstrap

```{r, warning = FALSE, message = FALSE}
generate_boots <- function(df, iter = 100, seeds = seed_vec){
  pb3$tick()
  boot_samples <- list()
  matched_boot_df <- list()
  boot_log_or <- tibble()
  
    for (i in 1:iter) {
      set.seed(seeds[[i]])
      
      boot_samples[[i]] <- sample_n(df, nrow(df), replace = TRUE)
      
      matched <- matchit(A ~ L1 + L2 + L3, data = boot_samples[[i]], 
                         distance = "glm", link = "logit",
                         method = "nearest", ratio = 1)
      
      matched_boot_df[[i]] <- match.data(matched, distance = "ps")
      
      bootmod <- glm(Y ~ A + ps, data = matched_boot_df[[i]], 
                     weights = weights, family = binomial)
      
      sum_bootmod <- summary(bootmod)
      
      estimate_val <- sum_bootmod$coef[2,1]
      to_bind_rows_estimate <- tibble(estimate = estimate_val)
      boot_log_or <- bind_rows(boot_log_or, to_bind_rows_estimate)
    }

       results <-
       tibble(
         mean_log_odds = mean(boot_log_or$estimate),
         sd_log_odds = sd(boot_log_or$estimate)
       )

  return(results)
}
```

## Run Complex Bootstrap

```{r}
nb_tib <- tibble(nb = no_boot_list)

pb3 <- progress_bar$new(format = "bootstrapping... [:bar] :percent eta: :eta", total = nrow(nb_tib))

result_list <- nb_tib %>% mutate(res_tib = map(.x = nb, ~generate_boots(.x, iter = 10)))

fin_estimate_df <- result_list %>% unnest(res_tib) %>% select(-nb)
```

## 1000 Confidence Intervals Coverage Rate

```{r}
ci_and_coverage <- function(fin_estimates){

    fin_estimates <- 
      fin_estimates %>% 
      mutate(lower_ci = mean_log_odds - 1.96*sd_log_odds,
             upper_ci = mean_log_odds + 1.96 * sd_log_odds,
             count_true = lower_ci <= 0.767 & 0.767 <= upper_ci)
  
  return(fin_estimates)
}
complex_coverage <- ci_and_coverage(fin_estimate_df)

coverage_rate <-  
    complex_coverage %>% 
    select(count_true) %>% 
    sum() %>% 
    paste0("%")
coverage_rate

complex_coverage <- complex_coverage %>% 
    mutate(seq = seq(1:nrow(complex_coverage)))
  
plot = complex_coverage %>% 
    ggplot(aes(x = mean_log_odds, y = seq)) +
    geom_point() +
    geom_errorbar(aes(xmin = lower_ci, xmax = upper_ci)) +
    geom_vline(xintercept = 0.767, linetype = "dashed")

plot
```






